name: My CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Just print a message
        run: echo "Starting the build process..."

      - name: Show all envs
        run: env

      - name: Checkout my-shared-library
        uses: actions/checkout@v4
        with:
          repository: BigCat3997/one-press-mock-projects

      - name: Install dependencies
        run: npm install