name: My CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Just print a message
        run: echo "Starting the build process..."

      - name: Show all envs
        run: env

      - name: Install dependencies
        run: npm install